title: Mirza Feberani
email: mirzafeberani.@gmail.com
description:  I study at the Lhokseumawe State Polytechnic as a student in the Information and Technology Department. I come from Bener Meriah.  
              I am the fourth child out of three siblings. I graduated from the Bener Meriah Superior High School. Currently, my hobby is exercising,  
              especially playing football.

url: "https://mirzafeberanyy.github.io"

plugins:
    - jekyll-feed
    - jekyll-sitemap
    - jekyll-seo-tag  